# Workflow para executar testes Playwright e publicar apenas o relatório HTML como artifact
# Não gera PDF nem executa scripts de geração de PDF
name: Playwright Tests

on:
  push:
    branches: [main, test-login]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    env:
      SAUCE_USER: ${{ secrets.SAUCE_USER }}
      SAUCE_SENHA: ${{ secrets.SAUCE_SENHA }}
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug: show presence of SAUCE_ env vars (no secret values)
        run: |
          if [ -n "${SAUCE_USER}" ]; then
            echo "SAUCE_USER set: yes"
          else
            echo "SAUCE_USER set: no"
          fi
          if [ -n "${SAUCE_SENHA}" ]; then
            echo "SAUCE_SENHA set: yes"
          else
            echo "SAUCE_SENHA set: no"
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (reporters via config)
        id: playwright_test
        run: |
          npx playwright test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload test-results (videos/screenshots/traces)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

# Observações:
# - Os artifacts poderão ser baixados na aba 'Actions' > executar workflow > 'Artifacts'.
# - Não há etapa para gerar PDF; removi qualquer chamada a scripts .github/scripts/*.js.
# - Caso precise executar em outra branch além de main, adicione a branch ao gatilho 'branches' acima.
# - Adicione os secrets 'SAUCE_USER' e 'SAUCE_SENHA' nas Settings -> Secrets and variables -> Actions no repositório.
