# Workflow para executar testes Playwright e publicar apenas o relatório HTML como artifact
# Não gera PDF nem executa scripts de geração de PDF
name: Playwright Tests

on:
  push:
    branches: [main, test-login]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env from repository secrets
        # Cria um arquivo .env na raiz do repositório no runner a partir de secrets configurados no GitHub
        run: |
          echo "USER=${{ secrets.USER }}" > .env
          echo "SENHA=${{ secrets.SENHA }}" >> .env
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Versão do Node utilizada no projeto (ajuste se necessário)
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        # Instala navegadores e dependências necessárias
        run: npx playwright install --with-deps

      - name: Run Playwright tests (reporters via config)
        id: playwright_test
        # Executa os testes; o reporter HTML está configurado em playwright.config.ts
        run: |
          npx playwright test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

# Observações:
# - Os artifacts poderão ser baixados na aba 'Actions' > executar workflow > 'Artifacts'.
# - Não há etapa para gerar PDF; removi qualquer chamada a scripts .github/scripts/*.js.
# - Caso precise executar em outra branch além de main, adicione a branch ao gatilho 'branches' acima.
# - Adicione os secrets 'USER' e 'SENHA' nas Settings -> Secrets and variables -> Actions no repositório.
