name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/allure-report
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    name: Run Playwright tests and publish Allure to gh-pages
    runs-on: ubuntu-latest
    env:
      SAUCE_USER: ${{ secrets.SAUCE_USER }}
      SAUCE_SENHA: ${{ secrets.SAUCE_SENHA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # necessário para preservar histórico do gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        # Garante que as próximas etapas executem mesmo com falhas nos testes
        continue-on-error: true

      - name: Upload test-results (videos/screenshots/traces)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Set up JDK (Zulu 17)
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
            ref: gh-pages
            path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
            gh_pages: gh-pages
            allure_history: allure-history
            allure_results: build/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history



